#!/usr/bin/env tsx
/**
 * Apply pending database migrations.
 *
 * Two-phase strategy:
 *   1. Run the hand-authored `0000_init.sql` bootstrap if the database is
 *      empty. This file contains things Drizzle can't diff: HNSW index with
 *      operator class, tsvector trigger, partial indexes. The file is
 *      idempotent (CREATE IF NOT EXISTS, DO blocks) so reruns are no-ops.
 *
 *   2. Hand off to Drizzle's official migrator for every subsequent file
 *      generated by `drizzle-kit generate`. Drizzle tracks applied
 *      migrations in `__drizzle_migrations__`, so re-running this command
 *      is safe and only applies what's pending.
 *
 * `applyMigrations` is exported so callers other than the CLI (namely
 * `tests/e2e`'s Vitest globalSetup) can run the SAME two-phase logic instead
 * of hand-rolling a subset of it. A prior version of the e2e harness
 * duplicated only phase 1, which silently left every column/table added
 * after `0000_init.sql` missing in CI's byte-fresh Postgres service
 * container (masked in local dev, where a persistent docker volume usually
 * already has everything applied from a previous manual `pnpm db:migrate`).
 *
 * Run with: pnpm db:migrate
 */
import { readFile, realpath } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { sql } from "drizzle-orm";
import pg from "pg";

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(__dirname, "..", "drizzle");

export async function applyMigrations(databaseUrl: string): Promise<void> {
  const pool = new pg.Pool({ connectionString: databaseUrl, max: 2 });

  try {
    // Phase 1: idempotent bootstrap — runs against any database, every time.
    // Safe because every statement in 0000_init.sql uses IF NOT EXISTS or
    // DO blocks with EXCEPTION handling.
    const bootstrap = await readFile(
      join(migrationsDir, "0000_init.sql"),
      "utf8",
    );
    process.stdout.write("→ applying 0000_init.sql (bootstrap)\n");
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query(bootstrap);
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }

    // Phase 2: Drizzle's migrator processes everything listed in
    // `drizzle/meta/_journal.json` and tracks applied files in
    // `__drizzle_migrations__`.
    //
    // IMPORTANT: `0000_init.sql` is intentionally NOT listed in the journal.
    // It contains `DO $$ ... $$` blocks and triggers that Drizzle's
    // statement-breakpoint parser cannot split correctly. Phase 1 above runs
    // it as a single transaction-safe blob instead. Any new schema change
    // generated by `drizzle-kit generate` will produce a Drizzle-formatted
    // SQL file PLUS update the journal — those are safe for Phase 2.
    process.stdout.write("→ running drizzle migrator for pending files\n");
    const db = drizzle(pool);
    await migrate(db, { migrationsFolder: migrationsDir });

    // Smoke test: verify the schema is reachable.
    await db.execute(sql`SELECT 1`);
    process.stdout.write("✓ Migrations complete\n");
  } finally {
    await pool.end();
  }
}

async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    process.stderr.write("DATABASE_URL is not set\n");
    process.exit(1);
  }
  await applyMigrations(url);
}

// Only auto-run when executed directly (`tsx src/migrate.ts`, or
// `node dist/migrate.js` from a production bundle) — importing this module
// as a library (e.g. from `tests/e2e`) must not also trigger a CLI run
// against `process.env.DATABASE_URL`.
//
// Both `realpath` AND `pathToFileURL` are load-bearing, not just the latter.
// A naive `import.meta.url === \`file://${process.argv[1]}\`` comparison (the
// original code) silently fails whenever the entry script is reached through
// a symlink — exactly pnpm's `node_modules` layout, and exactly what
// `pnpm deploy --prod` produces for Railway's runtime image. Node resolves
// `import.meta.url` to the module's REAL (symlink-resolved) path, but
// `process.argv[1]` stays as whatever literal path was typed on the command
// line — `pathToFileURL(process.argv[1])` alone still doesn't match, because
// it only reformats the string, it doesn't resolve symlinks.
//
// Confirmed both the failure and this fix via direct reproduction (not just
// against the real `rag-worker` container, which is why the first attempt
// at this fix — pathToFileURL alone — looked plausible but didn't actually
// work): symlinking a copy of this package's directory and invoking
// `node <symlink>/dist/migrate.js` reproduces the exact silent exit-0
// no-op with the naive comparison, and confirms `realpath` first is what
// actually closes the gap. A database migration that silently no-ops
// instead of running, or instead of erroring, is worse than either
// alternative — this is why the guard gets this much scrutiny.
const invokedPath = process.argv[1];
const isDirectRun = invokedPath
  ? pathToFileURL(await realpath(invokedPath).catch(() => invokedPath)).href ===
    import.meta.url
  : false;
if (isDirectRun) {
  main().catch((err: unknown) => {
    process.stderr.write(
      `Migration failed: ${(err as Error).stack ?? String(err)}\n`,
    );
    process.exit(1);
  });
}
