/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse
         * @description Convert any supported document to clean markdown + structured metadata.
         *
         *     Routing:
         *       1. .xlsx / .xls       → openpyxl with data_only=True (computed values);
         *                               per-sheet classifier; structured headers+rows.
         *       2. .csv / .tsv        → stdlib csv with delimiter sniffing.
         *       3. Everything else    → MarkItDown first, Unstructured fallback.
         *
         *     The caller should supply the original filename in the `filename` form field
         *     so we can route by extension when MIME sniffing is ambiguous (e.g. legacy
         *     .doc looks the same as application/octet-stream).
         */
        post: operations["parse_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_parse_post */
        Body_parse_parse_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Filename */
            filename?: string | null;
            /** Mime Type */
            mime_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ParsedDocument */
        ParsedDocument: {
            /** Title */
            title: string;
            /** Markdown */
            markdown: string;
            /** Tables */
            tables?: components["schemas"]["ParsedTable"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ParsedTable */
        ParsedTable: {
            /** Markdown */
            markdown: string;
            /** Caption */
            caption?: string | null;
            /** Sheetname */
            sheetName?: string | null;
            /** Sheettype */
            sheetType?: ("tabular" | "narrative" | "financial_model" | "freeform") | null;
            /** Headers */
            headers?: string[];
            /** Rows */
            rows?: string[][];
            /**
             * Rowcount
             * @default 0
             */
            rowCount: number;
            /**
             * Columncount
             * @default 0
             */
            columnCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    parse_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
